name: pnpm Example Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: replicaDB
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: replicaDB/pnpm-lock.yaml
    - name: Install dependencies
      run: pnpm install
    - name: Create build directory
      run: pnpm run build
    - name: Upload build directory
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: replicaDB
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Download build directory
        uses: actions/download-artifact@v3
        with:
          name: build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
